<?php
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Comment
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Comment show comments list and form view script
 * 
 * @package    Comment
 */
?>
<hr />
<div id="comments">
<h3>Kommentare</h3>
</div>
<hr />
<div id="comment-form">
<h3>Neuen Kommentar schreiben</h3>
</div>
