<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Listings - Kapitel 19');
$this->pageTitle('Listings - Kapitel 19');
?>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing1901">Listing 19.1</a></td>
<td>Aufbau der Datenbank</td>
</tr>
<tr>
<td><a href="/listing/listing1902">Listing 19.2</a></td>
<td>Konfigurationsparameter in <code>module.config.php</code></td>
</tr>
<tr>
<td><a href="/listing/listing1903">Listing 19.3</a></td>
<td>Factory-Klasse übergibt Konfigurationsparameter an <code>CommentService</code></td>
</tr>
<tr>
<td><a href="/listing/listing1904">Listing 19.4</a></td>
<td><code>CommentService</code> verwendet Konfigurationsparameter</td>
</tr>
<tr>
<td><a href="/listing/listing1905">Listing 19.5</a></td>
<td><code>CommentTable</code> beachtet nur freigeschaltete Kommentare</td>
</tr>
<tr>
<td><a href="/listing/listing1906">Listing 19.6</a></td>
<td><code>CommentShowLinks</code> View-Helper zur Ausgabe von Zähler und Links</td>
</tr>
<tr>
<td><a href="/listing/listing1907">Listing 19.7</a></td>
<td>View-Skript <code>links.phtml</code> gibt Anzahl Kommentare und Links aus</td>
</tr>
<tr>
<td><a href="/listing/listing1908">Listing 19.8</a></td>
<td><code>CommentShowComments</code> View-Helper für Kommentare und Formular</td>
</tr>
<tr>
<td><a href="/listing/listing1909">Listing 19.9</a></td>
<td>View-Skript <code>comments.phtml</code> gibt Kommentare und Formular aus</td>
</tr>
<tr>
<td><a href="/listing/listing1910">Listing 19.10</a></td>
<td>Einbindung vom <code>CommentShowLinks</code> View-Helper</td>
</tr>
<tr>
<td><a href="/listing/listing1911">Listing 19.11</a></td>
<td>Einbindung vom <code>CommentShowComments</code> View-Helper</td>
</tr>
<tr>
<td><a href="/listing/listing1912">Listing 19.12</a></td>
<td><code>CommentController</code> zum Verarbeiten neuer Kommentare</td>
</tr>
<tr>
<td><a href="/listing/listing1913">Listing 19.13</a></td>
<td>Geänderter <code>CommentService</code> zum Speichern des Formular-Objekts</td>
</tr>
<tr>
<td><a href="/listing/listing1914">Listing 19.14</a></td>
<td>Geänderter <code>CommentShowComments</code> View-Helper</td>
</tr>
</tbody>
</table>
