<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 19.14 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 19.14');
$this->pageTitle('Listing 19.14');
?>
<h3>Geänderter <code>CommentShowComments</code> View-Helper</h3>
<pre>
&lt;?php
namespace Comment\View\Helper;

[...]

class CommentShowComments extends AbstractHelper
{
    [...]
    
    public function __invoke($url)
    {
        $commentForm = $this->getCommentService()->prepareCreateForm($url);
        
        [...]
    }
}
</pre>
