<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 19.1 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 19.1');
$this->pageTitle('Listing 19.1');
?>
<h3>Aufbau der Datenbank</h3>
<pre>
CREATE TABLE comments (
    id integer primary key, 
    cdate datetime, 
    status varchar(8), 
    url varchar(255), 
    email varchar(128), 
    name varchar(64), 
    message text
);
</pre>
