<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 19.5 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 19.5');
$this->pageTitle('Listing 19.5');
?>
<h3><code>CommentTable</code> beachtet nur freigeschaltete Kommentare</h3>
<pre>
&lt;?php 
namespace Comment\Table;

[...]

class CommentTable extends TableGateway implements CommentTableInterface
{
    [...]
    
    public function fetchListByUrl($url)
    {
        $select = $this->getSql()->select();
        $select->where->equalTo('url', $url);
        $select->where->equalTo('status', 'approved');
        $select->order('cdate ASC');
        
        return $this->selectWith($select);
    }
    
    public function fetchCountByUrl($url)
    {
        $select = $this->getSql()->select();
        $select->where->equalTo('url', $url);
        $select->where->equalTo('status', 'approved');
        
        return $this->selectWith($select)->count();
    }
    
    [...]
}
</pre>
