<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 19.11 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 19.11');
$this->pageTitle('Listing 19.11');
?>
<h3>Einbindung vom <code>CommentShowComments</code> View-Helper</h3>
<pre>
&lt;?php
$urlComment = $this-&gt;url('pizza/url', array(), array(), true);
?&gt;
[...]
&lt;?php if ($this-&gt;getHelperPluginManager()-&gt;has('commentShowLinks')) : ?&gt;
&lt;?php echo $this-&gt;commentShowLinks($urlComment); ?&gt;
&lt;?php endif; ?&gt;
[...]
&lt;?php if ($this-&gt;getHelperPluginManager()-&gt;has('commentShowComments')) : ?&gt;
&lt;?php echo $this-&gt;commentShowComments($urlComment); ?&gt;
&lt;?php endif; ?&gt;
</pre>
