<?php 
/**
 * ZF2 Buch Kapitel 19
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 19.2 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 19.2');
$this->pageTitle('Listing 19.2');
?>
<h3>Konfigurationsparameter in <code>module.config.php</code></h3>
<pre>
&lt;?php 
return array(
    [...]
    
    'comment' => array(
        'newStatus' => 'approved',
    ),
);
</pre>
